### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by Mert18** [Mert18/capacitive-piano-arduino#5]
Things need to be done:

- [x] Create the keyboard. #1 
- [x] Connect keyboard with Arduino, make sure arduino detects different keys. #2 
- [x] Play sound on different keys #3
